"use client";

/**
 * The briefing: what the representative enters for it, and the button that lays it out.
 *
 * Reached from the event switcher's list, the pattern of sessions 8 through 10. One
 * screen, sections in the order the document will have them (plan §3.2 as amended by
 * ADR-0009): the event and its dossier; the contacts; the attendees, each a door into
 * the attendee view where the photo and the briefing notes are edited; then Generate.
 *
 * GENERATE WRITES NO RECORD. Nothing here is generated by a model — the document is laid
 * out from stored records — so ADR-0009 says there is no audit record, and there is
 * none. The PDF is built in memory and handed to the browser as a download, the same
 * pattern as the audit-log CSV; no network, no share target. What she does with the
 * file afterwards is her action in her own mail client.
 *
 * THE DICTATED NOTES ARE NOT IN IT. They were captured for follow-ups. The briefing
 * carries the record's fields, the photo, and what she wrote for the briefing; the copy
 * says so, here and on the attendee view.
 */

import { useEffect, useMemo, useState } from "react";

import { composeBriefing } from "@/lib/briefing/compose";
import { renderBriefing } from "@/lib/briefing/render";
import {
  createContact,
  getImage,
  listContacts,
  listImages,
  removeContact,
  updateContact,
  updateEventDossier,
  type AttendeeRecord,
  type ContactInput,
  type ContactRecord,
  type EventDossier,
  type EventRecord,
  type ImageRecord,
} from "@/lib/db";
import { downloadBytes, slugOf } from "@/lib/download";
import { dataUrlOf } from "@/lib/images/data-url";

const DOSSIER_FIELDS: ReadonlyArray<[keyof EventDossier, string, string]> = [
  ["objectives", "Objectives", "What the visit is for."],
  ["configuration", "Configuration", "The room, the equipment, the set-up."],
  ["itinerary", "Itinerary", "Times and what happens at each."],
  ["logistics", "Logistics", "Parking, access, badges, who to ask for."],
  [
    "contingency",
    "Contingency plan",
    "What to do if something goes wrong. Last on the page.",
  ],
];

const EMPTY_CONTACT: ContactInput = {
  name: "",
  function: "",
  phone: "",
  email: "",
  notes: "",
};

function dossierOf(event: EventRecord): EventDossier {
  return {
    objectives: event.objectives,
    configuration: event.configuration,
    itinerary: event.itinerary,
    logistics: event.logistics,
    contingency: event.contingency,
  };
}

export interface BriefingScreenProps {
  event: EventRecord;
  attendees: AttendeeRecord[];
  /** The dossier was saved; the caller holds the event and re-reads it. */
  onEventChanged: (event: EventRecord) => void;
  /** Opens the attendee view, where the photo and the briefing notes are edited. */
  onOpenAttendee: (attendee: AttendeeRecord) => void;
  onClose: () => void;
}

export function BriefingScreen({
  event,
  attendees,
  onEventChanged,
  onOpenAttendee,
  onClose,
}: BriefingScreenProps) {
  const [dossier, setDossier] = useState<EventDossier>(dossierOf(event));
  const [dossierState, setDossierState] = useState<"idle" | "saving" | "saved" | "error">(
    "idle",
  );
  const [contacts, setContacts] = useState<ContactRecord[]>([]);
  const [photos, setPhotos] = useState<Map<string, ImageRecord>>(new Map());
  const [siteMap, setSiteMap] = useState<ImageRecord | null>(null);
  const [editingContact, setEditingContact] = useState<"none" | "new" | string>("none");
  const [contactDraft, setContactDraft] = useState<ContactInput>(EMPTY_CONTACT);
  const [contactError, setContactError] = useState<string | null>(null);
  const [generating, setGenerating] = useState(false);
  const [generateError, setGenerateError] = useState<string | null>(null);

  useEffect(() => {
    setDossier(dossierOf(event));
  }, [event]);

  useEffect(() => {
    let cancelled = false;
    void listContacts(event.id).then((loaded) => {
      if (!cancelled) setContacts(loaded);
    });
    void getImage(event.id, "site-map").then((stored) => {
      if (!cancelled) setSiteMap(stored ?? null);
    });
    return () => {
      cancelled = true;
    };
  }, [event.id]);

  useEffect(() => {
    let cancelled = false;
    void listImages(
      attendees.map((a) => a.id),
      "attendee-photo",
    ).then((loaded) => {
      if (!cancelled) setPhotos(loaded);
    });
    return () => {
      cancelled = true;
    };
  }, [attendees]);

  const thumbnails = useMemo(() => {
    const out = new Map<string, string>();
    for (const [ownerId, image] of photos)
      out.set(ownerId, dataUrlOf(image.bytes, image.mediaType));
    return out;
  }, [photos]);

  const dossierDirty = DOSSIER_FIELDS.some(([key]) => dossier[key] !== event[key]);

  const saveDossier = async () => {
    setDossierState("saving");
    try {
      const updated = await updateEventDossier(event.id, dossier);
      onEventChanged(updated);
      setDossierState("saved");
    } catch {
      setDossierState("error");
    }
  };

  const openContact = (target: "new" | ContactRecord) => {
    setContactError(null);
    if (target === "new") {
      setEditingContact("new");
      setContactDraft(EMPTY_CONTACT);
    } else {
      setEditingContact(target.id);
      setContactDraft({
        name: target.name,
        function: target.function,
        phone: target.phone,
        email: target.email,
        notes: target.notes,
      });
    }
  };

  const saveContact = async () => {
    setContactError(null);
    try {
      if (editingContact === "new") await createContact(event.id, contactDraft);
      else if (editingContact !== "none")
        await updateContact(editingContact, contactDraft);
      setContacts(await listContacts(event.id));
      setEditingContact("none");
      setContactDraft(EMPTY_CONTACT);
    } catch (cause) {
      setContactError(cause instanceof Error ? cause.message : String(cause));
    }
  };

  const deleteContact = async (contact: ContactRecord) => {
    await removeContact(contact.id);
    if (editingContact === contact.id) setEditingContact("none");
    setContacts(await listContacts(event.id));
  };

  const generate = async () => {
    setGenerating(true);
    setGenerateError(null);
    try {
      const generatedAt = Date.now();
      const document = composeBriefing({
        event,
        contacts,
        attendees: attendees.map((attendee) => ({
          attendee,
          photo: photos.get(attendee.id) ?? null,
        })),
        siteMap,
        generatedAt,
      });
      const bytes = await renderBriefing(document);
      const stamp = new Date(generatedAt).toISOString().slice(0, 10);
      downloadBytes(
        bytes,
        `briefing-${slugOf(event.name)}-${stamp}.pdf`,
        "application/pdf",
      );
    } catch (cause) {
      setGenerateError(cause instanceof Error ? cause.message : String(cause));
    } finally {
      setGenerating(false);
    }
  };

  const sortedAttendees = [...attendees].sort((a, b) =>
    a.displayName.localeCompare(b.displayName),
  );

  return (
    <section
      data-testid="briefing"
      aria-label="Briefing"
      className="flex flex-col gap-5 p-4"
    >
      <div className="flex items-center justify-between gap-3">
        <h2 className="text-base font-semibold">Briefing</h2>
        <button
          type="button"
          data-testid="briefing-close"
          onClick={onClose}
          className="min-h-11 rounded-lg border px-4 text-sm"
        >
          Back to notes
        </button>
      </div>

      <p className="text-xs opacity-70">
        An internal document for your own team, laid out from what you enter here and on
        each person&apos;s page. Nothing in it is written by the model, and nothing is
        sent: Generate saves a PDF to this phone, and you send it yourself. The notes you
        dictated are not in it.
      </p>

      {/* 1. Event */}
      <form
        data-testid="briefing-event"
        className="flex flex-col gap-3"
        onSubmit={(submit) => {
          submit.preventDefault();
          if (dossierDirty && dossierState !== "saving") void saveDossier();
        }}
      >
        <h3 className="text-sm font-semibold">1. Event</h3>
        <p className="text-sm">
          <span className="font-medium">{event.name}</span>
          {event.startsAt !== null
            ? ` · ${new Date(event.startsAt).toLocaleDateString(undefined, {
                day: "numeric",
                month: "short",
                year: "numeric",
              })}`
            : ""}
          {event.siteLabel ? ` · ${event.siteLabel}` : ""}
        </p>
        <p data-testid="briefing-site-map-state" className="text-xs opacity-60">
          {siteMap
            ? "A site map is stored for this event and goes on the briefing. It is edited on the pre-event email screen."
            : "No site map yet. One can be added on the pre-event email screen, and goes on the briefing too."}
        </p>
        {DOSSIER_FIELDS.map(([key, label, hint]) => (
          <label key={key} className="flex flex-col gap-1 text-sm">
            <span className="font-medium">{label}</span>
            <textarea
              data-testid={`briefing-${key}`}
              value={dossier[key]}
              onChange={(change) => {
                setDossierState("idle");
                setDossier({ ...dossier, [key]: change.target.value });
              }}
              placeholder={hint}
              className="h-20 w-full resize-none rounded-lg border p-3 text-base leading-relaxed"
            />
          </label>
        ))}
        <div className="flex items-center justify-between gap-3">
          <p data-testid="briefing-event-state" className="text-xs opacity-60">
            {dossierState === "saving"
              ? "Saving…"
              : dossierState === "saved"
                ? "Saved"
                : dossierState === "error"
                  ? "Not saved"
                  : dossierDirty
                    ? "Not saved yet"
                    : ""}
          </p>
          <button
            type="submit"
            data-testid="briefing-event-save"
            disabled={!dossierDirty || dossierState === "saving"}
            className="min-h-11 rounded-lg border px-4 text-base font-medium disabled:opacity-40"
          >
            Save
          </button>
        </div>
      </form>

      {/* 2. Contacts */}
      <div data-testid="briefing-contacts" className="flex flex-col gap-3">
        <h3 className="text-sm font-semibold">2. Contacts</h3>
        <p className="text-xs opacity-60">
          Your own team, the site coordinator, the truck operator, transportation. These
          people are on the briefing only; no follow-up is ever drafted to them.
        </p>
        {contacts.length === 0 && editingContact === "none" && (
          <p data-testid="briefing-contacts-empty" className="text-sm opacity-60">
            No contacts yet.
          </p>
        )}
        <ul className="flex flex-col gap-2">
          {contacts.map((contact) => (
            <li
              key={contact.id}
              data-testid="briefing-contact"
              className="flex flex-col gap-1 rounded-lg border border-black/10 p-3 text-sm dark:border-white/15"
            >
              <span className="font-medium">{contact.name}</span>
              <span className="text-xs opacity-70">
                {[contact.function, contact.phone, contact.email]
                  .filter(Boolean)
                  .join(" · ")}
              </span>
              {contact.notes && <span className="text-xs">{contact.notes}</span>}
              <span className="flex gap-2">
                <button
                  type="button"
                  data-testid="briefing-contact-edit"
                  onClick={() => openContact(contact)}
                  className="min-h-11 rounded-lg border px-3"
                >
                  Edit
                </button>
                <button
                  type="button"
                  data-testid="briefing-contact-remove"
                  onClick={() => void deleteContact(contact)}
                  className="min-h-11 rounded-lg border px-3"
                >
                  Remove
                </button>
              </span>
            </li>
          ))}
        </ul>
        {editingContact === "none" ? (
          <button
            type="button"
            data-testid="briefing-contact-add"
            onClick={() => openContact("new")}
            className="min-h-11 self-start rounded-lg border px-4 text-base font-medium"
          >
            Add a contact
          </button>
        ) : (
          <form
            data-testid="briefing-contact-form"
            className="flex flex-col gap-3"
            onSubmit={(submit) => {
              submit.preventDefault();
              void saveContact();
            }}
          >
            {(
              [
                ["name", "Name"],
                ["function", "Function"],
                ["phone", "Phone"],
                ["email", "Email"],
                ["notes", "Notes"],
              ] as const
            ).map(([key, label]) => (
              <label key={key} className="flex flex-col gap-1 text-sm">
                <span className="font-medium">{label}</span>
                <input
                  data-testid={`briefing-contact-${key}`}
                  value={contactDraft[key]}
                  onChange={(change) =>
                    setContactDraft({ ...contactDraft, [key]: change.target.value })
                  }
                  autoComplete="off"
                  className="min-h-11 rounded-lg border px-3 text-base"
                />
              </label>
            ))}
            {contactError && (
              <p
                data-testid="briefing-contact-error"
                role="alert"
                className="text-sm text-red-600"
              >
                {contactError}
              </p>
            )}
            <div className="flex gap-2">
              <button
                type="submit"
                data-testid="briefing-contact-save"
                disabled={contactDraft.name.trim().length === 0}
                className="min-h-11 rounded-lg border px-4 text-base font-medium disabled:opacity-40"
              >
                {editingContact === "new" ? "Add" : "Save"}
              </button>
              <button
                type="button"
                data-testid="briefing-contact-cancel"
                onClick={() => setEditingContact("none")}
                className="min-h-11 rounded-lg border px-4 text-base"
              >
                Cancel
              </button>
            </div>
          </form>
        )}
      </div>

      {/* 3. Attendees */}
      <div data-testid="briefing-attendees" className="flex flex-col gap-3">
        <h3 className="text-sm font-semibold">3. Attendees</h3>
        <p data-testid="briefing-attendees-note" className="text-xs opacity-60">
          Expected attendance as of today. People met at the event who are not on this
          list will not appear in the briefing. Open a person to add a photo and your
          notes for them.
        </p>
        {sortedAttendees.length === 0 ? (
          <p className="text-sm opacity-60">Nobody yet.</p>
        ) : (
          <ul className="flex flex-col gap-2">
            {sortedAttendees.map((attendee) => (
              <li key={attendee.id}>
                <button
                  type="button"
                  data-testid="briefing-attendee"
                  data-attendee-id={attendee.id}
                  data-has-photo={thumbnails.has(attendee.id) ? "true" : "false"}
                  onClick={() => onOpenAttendee(attendee)}
                  className="flex min-h-14 w-full items-center gap-3 rounded-lg border border-black/10 p-3 text-left dark:border-white/15"
                >
                  {thumbnails.has(attendee.id) ? (
                    // Local bytes as a data: URL, not a remote image.
                    // eslint-disable-next-line @next/next/no-img-element
                    <img
                      src={thumbnails.get(attendee.id)}
                      alt=""
                      className="h-12 w-12 rounded object-cover"
                    />
                  ) : (
                    <span className="flex h-12 w-12 items-center justify-center rounded border border-dashed border-black/20 text-[10px] opacity-60 dark:border-white/25">
                      No photo
                    </span>
                  )}
                  <span className="flex flex-col">
                    <span className="font-medium">{attendee.displayName}</span>
                    <span className="text-xs opacity-70">
                      {[attendee.role, attendee.specialty, attendee.institution]
                        .filter(Boolean)
                        .join(" · ") || "No details yet"}
                      {attendee.briefingNotes.trim()
                        ? " · notes written"
                        : " · no notes yet"}
                    </span>
                  </span>
                </button>
              </li>
            ))}
          </ul>
        )}
      </div>

      {/* 4. Generate */}
      <div data-testid="briefing-generate-section" className="flex flex-col gap-2">
        <h3 className="text-sm font-semibold">4. Generate</h3>
        <p className="text-xs opacity-60">
          Builds the PDF from what is saved above and on each person&apos;s page, and
          saves it to this phone. Nothing is sent, and no record is written: nothing here
          was generated by a model.
        </p>
        <button
          type="button"
          data-testid="briefing-generate"
          onClick={() => void generate()}
          disabled={generating}
          className="min-h-11 self-start rounded-lg border px-4 text-base font-medium disabled:opacity-40"
        >
          {generating ? "Building…" : "Generate the briefing PDF"}
        </button>
        {generateError && (
          <p
            data-testid="briefing-generate-error"
            role="alert"
            className="text-sm text-red-600"
          >
            {generateError}
          </p>
        )}
      </div>
    </section>
  );
}
