/**
 * Public surface of the data-access layer.
 *
 * Application code imports from `@/lib/db` and nothing deeper. Dexie itself is reachable
 * only through `database.ts` and `migrations.ts`; see `tests/unit/db-boundary.test.ts`,
 * which fails the build if anything outside this directory imports it.
 */

export {
  identityCipher,
  getCipher,
  setCipher,
  resetCipher,
  encryptRecord,
  decryptRecord,
  decryptAll,
  type FieldCipher,
} from "./cipher";

export { isPersistenceAvailable } from "./database";

export { MIGRATIONS, LATEST_MIGRATION_VERSION } from "./migrations";

export {
  CURRENT_SCHEMA_VERSION,
  DEFAULT_AUTOSAVE_DEBOUNCE_MS,
  TABLES,
  POLICIES_BY_TABLE,
  eligibleFields,
  type Id,
  type EncryptionClass,
  type FieldPolicy,
  type FieldShape,
  type FieldPolicies,
  type BaseRecord,
  type EventRecord,
  type EventStatus,
  type AttendeeRecord,
  type AttendeeKind,
  type AttendeeSource,
  type NoteRecord,
  type NoteSource,
  type DraftRecord,
  type DraftKind,
  type DraftState,
  type DraftBlockReason,
  type AuditRecordRecord,
  type VoiceProfileRecord,
  type ApprovedContentRecord,
  type ImageRecord,
  type ImagePurpose,
  type ContactRecord,
  type SettingsRecord,
  type SessionMarkerRecord,
  type TableName,
} from "./schema";

export {
  createEvent,
  getEvent,
  listEvents,
  deleteEvent,
  updateEventDossier,
  type EventDossier,
  updateEventLocation,
  type EventLocation,
  updateEventTimes,
  type EventTimes,
  saveAttendeeBriefingNotes,
  deleteAttendee,
  putImage,
  getImage,
  listImages,
  removeImage,
  type NewImageInput,
  createContact,
  listContacts,
  updateContact,
  removeContact,
  type ContactInput,
  createAttendee,
  listAttendees,
  getAttendee,
  listAllAttendees,
  updateAttendee,
  listNotesForAttendee,
  listDraftsForAttendee,
  applyRosterImport,
  listApprovedContent,
  addApprovedContent,
  updateApprovedContent,
  removeApprovedContent,
  type NewApprovedContentInput,
  type AttendeeEdit,
  type AttendeeDetails,
  type RosterImportDecision,
  type RosterImportResult,
  createNote,
  getNote,
  listNotes,
  saveNoteBody,
  attributeNote,
  createDraftWithAudit,
  getDraft,
  listDrafts,
  saveDraftBody,
  markReviewed,
  exportDraft,
  getAuditRecordForDraft,
  listAuditRecords,
  getActiveEventId,
  setActiveEventId,
  type NewEventInput,
  type NewAttendeeInput,
  type NewNoteInput,
  type NewDraftInput,
  type DraftWithAudit,
} from "./repository";

export { kindFromTitle, kindFromDisplayName } from "./attendee-kind";

export {
  DRAFT_TRANSITIONS,
  DraftStateError,
  assertTransition,
  canEdit,
  canExport,
  canTransition,
  reachableFrom,
} from "./draft-state";

export {
  beginSession,
  endSession,
  resumeSession,
  recordTouchedNote,
  acknowledgeRecovery,
  resetSessionState,
  HEARTBEAT_MS,
  type SessionHandle,
  type RecoveredSession,
} from "./recovery";
